# Generated by Django 2.1 on 2018-08-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableset',
            name='free_service',
            field=models.IntegerField(default=0),
        ),
    ]
