# Generated by Django 2.1 on 2018-08-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tableset_free_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableset',
            name='test_store',
            field=models.IntegerField(default=0),
        ),
    ]
