# Generated by Django 2.1 on 2018-08-31 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180830_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credits',
            name='credits',
            field=models.IntegerField(default=75000),
        ),
    ]
